name: Docker Build and Push Workflow v3

on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: true
      docker_password:
        description: 'Docker Hub Password or Personal Access Token (PAT)'
        required: true
      image_name:
        description: 'Docker image name (e.g., myimage)'
        required: true
        default: 'tgstremio'
      image_tag:
        description: 'Docker image tag (e.g., latest, v1.0)'
        required: true
        default: 'v1'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ github.event.inputs.docker_username }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}
